language: python

python:
  - '2.7'

install: pip install -r requirements.txt

script: make test

notifications:
  email:
    recipients:
      - benjamin.bengfort@georgetown.edu
      - allen.leis@georgetown.edu
      - anthony.ojeda@georgetown.edu
    on_success: change
    on_failure: always
